-- employees 테이블에서 전체 내용 조회
SELECT  *
FROM EMPLOYEES e ;

-- first_name, last_name, job_id 조회
SELECT first_name, last_name, job_id
FROM EMPLOYEES e ;



--사원 번호가 176인 사람의 LAST_NAME 과 DEPARTMENT_ID 조회

SELECT * 

FROM EMPLOYEES e 

--연봉이 12000 이상 되는 직원들의  LAST_NAME 과  SALARY 조회

--연봉이 5000에서  12000의 범위 이외인 사람들의 lAST NAME과 SALARY 조회


--2017-01-01 ~ 2017-12-31 사이에 고용된 사원들의 LAST_NAME,EMPLOYEE_ID, HIRE.DATE 조회
--HIRE_DATE 내림차순 정렬
SELECT  LAST_NAME, EMPLOYEE_ID,HIRE_DATE
FROM EMPLOYEES e 
WHERE HIRE_DATE >= '2017-01-01'AND HIRE_DATE <='2017-12-31'

SELECT  LAST_NAME, EMPLOYEE_ID,HIRE_DATE
FROM EMPLOYEES e 
WHERE HIRE_DATE BETWEEN '2017-01-01'AND '2017-12-31';
ORDER BY HIRE_DATE ASC;


SELECT  LAST_NAME, EMPLOYEE_ID,HIRE_DATE
FROM EMPLOYEES e 
WHERE HIRE_DATE BETWEEN '2017-01-01'AND '2017-12-31'

--부서번호가 20,50 부서에서 근무하고 연봉이 5000~12000 사이인 사원들의 LAST_NAME, SALARY 조회
--SALARY 오름차순 정렬


SELECT LAST_NAME, SALARY
FROM EMPLOYEES e 
WHERE 


--FIRST_NAME 이  'curtis' 인 사원의  first_NAME, LAST_NAME, EAILL,PHON_NUMBER,JOB _ID 를 
--조회한다 .단 JOB_ID 는 소문자로 출력 된다

SELECT  FIRST_NAME,LAST_NAME,EMAIL ,PHONE_NUMBER ,LOWER(JOB_ID)
FROM EMPLOYEES e 
WHERE FIRST_NAME ='Curtis';

--부서 번호가 60 70 80 90 인 사원들의 employee_id, first_name,hire_date , job_id 조회

SELECT employee_id,first_name,hire_date,REPLACE (job_id,'IT_PROG','프로그래머')
FROM EMPLOYEES e 
WHERE DEPARTMENT_ID in(60,70,80,90);



SELECT  LAST_NAME 
FROM EMPLOYEES e 
WHERE LAST_NAME LIKE '%u%';

SELECT  LAST_NAME
FROM EMPLOYEES e 
WHERE LAST_NAME LIKE '%a%' OR LAST_NAME LIKE '%e%'
ORDER BY LAST_NAME DESC;


SELECT *
FROM EMPLOYEES e;












-







